#!/bin/bash

# Setup a symlink for the .screenrc to use for the agent. Allows re-connect of
# the agent after screen session disconects.
# http://superuser.com/questions/180148/how-do-you-get-screen-to-automatically-connect-to-the-current-ssh-agent-when-re-a
if test "$SSH_AUTH_SOCK" ; then
    ln -sf $SSH_AUTH_SOCK ~/.ssh/ssh_auth_sock
fi
