#!/usr/bin/perl -w
# vim:filetype=perl

=head1  NAME

mystery - Performs and unkown and possibley magic/lethal operation.

=cut

use strict;
use warnings;
require 5.6.0;
our $VERSION = 0.1;

use Getopt::Long;
use Pod::Usage;

our %Opts;

# Main
#=============================================================================

# Process options
#-----------------------------------------------------------------------------

# Defaults
# $opt{foo} = 'blah';

# Options
GetOptions(
    \%Opts,
    'help|h|?',
    'man',
    # more options!
) or pod2usage(2);
pod2usage(1) if exists $Opts{help};
pod2usage( -exitstatus => 0, -verbose => 2 ) if exists $Opts{man};

# Do stuff
#-----------------------------------------------------------------------------


__END__

=head1 SYNOPSIS

Blah blah, blah...

=head1 OPTIONS

=over 4

=item -h -? --help

Dislay help message and exit.

=item --man

Display man page and exit.

=back

=head1 DESCRIPTION

=head1 SEE ALSO

perl(1)

=head1 BUGS

Probably...

=head1 TODO

More testing...

=head1 AUTHOR

grommit <mark.addison@itn.co.uk> 

=head1 LICENSE

This package is free software and is provided "as is" without express or
implied warranty. It may be used, redistributed and/or modified under the
terms of either; 

a) the Perl Artistic License.

See F<http://www.perl.com/perl/misc/Artistic.html>

b) the terms of the GNU General Public License as published by the Free Software
Foundation; either version 1, or (at your option) any later version.

=cut
