---
# Ansible playbook to setup a desktop machine the way I like.
- hosts: localhost
  roles:
    - desktop
    - vim

# XPS laptop ubuntu
- hosts: ziller
  roles:
    - aws_developer
    #- display_link
    #- cocoon_developer
