---
# Ansible playbook to setup a desktop machine the way I like.
- hosts: localhost
  vars:
    packages:
      - vim
      - vim-gtk
      - tree
      - htop
      - terminator
      - xtail
      - ack-grep
      - wajig
      - ccze
      - idle
      - fonts-droid
      - kvpm
      - quicksynergy
      - synergy
      - synaptic
  tasks:
    - name: Install packages
      sudo: yes
      apt: name={{item}}
      with_items: packages